version: "3.8"

services:
  auth-pg:
    container_name: auth-pg
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: auth-db
    ports:
      - "15432:5432"
    restart: unless-stopped

  task-pg:
    container_name: task-pg
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: task-db
    ports:
      - "25432:5432"
    restart: unless-stopped